<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            ['DistrictID' => 1, 'DistrictName' => 'Ba Đình', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 2, 'DistrictName' => 'Hoàn Kiếm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 3, 'DistrictName' => 'Hai Bà Trưng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 4, 'DistrictName' => 'Đống Đa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 5, 'DistrictName' => 'Tây Hồ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 6, 'DistrictName' => 'Cầu Giấy', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 7, 'DistrictName' => 'Thanh Xuân', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 8, 'DistrictName' => 'Hoàng Mai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 9, 'DistrictName' => 'Long Biên', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 10, 'DistrictName' => 'Nam Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 11, 'DistrictName' => 'Bắc Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 12, 'DistrictName' => 'Hà Đông', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 13, 'DistrictName' => 'Sơn Tây', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 14, 'DistrictName' => 'Sóc Sơn', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 15, 'DistrictName' => 'Đông Anh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 16, 'DistrictName' => 'Gia Lâm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 17, 'DistrictName' => 'Thanh Trì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 18, 'DistrictName' => 'Mê Linh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 19, 'DistrictName' => 'Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 20, 'DistrictName' => 'Ba Vì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 21, 'DistrictName' => 'Chương Mỹ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 22, 'DistrictName' => 'Đan Phượng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 23, 'DistrictName' => 'Hoài Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 24, 'DistrictName' => 'Quốc Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 25, 'DistrictName' => 'Thạch Thất', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 26, 'DistrictName' => 'Thanh Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 27, 'DistrictName' => 'Thường Tín', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 28, 'DistrictName' => 'Ứng Hòa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 29, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 30, 'DistrictName' => 'Phúc Thọ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],         
            ['DistrictID' => 31, 'DistrictName' => 'Thành Phố Tân Phú', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 32, 'DistrictName' => 'Quận 1', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 33, 'DistrictName' => 'Quận 3', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 34, 'DistrictName' => 'Quận 4', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 35, 'DistrictName' => 'Quận 5', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 36, 'DistrictName' => 'Quận 6', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 37, 'DistrictName' => 'Quận 7', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 38, 'DistrictName' => 'Quận 8', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 39, 'DistrictName' => 'Quận 10', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 40, 'DistrictName' => 'Quận 11', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 41, 'DistrictName' => 'Quận 12', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 42, 'DistrictName' => 'Quận Bình Tân', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 43, 'DistrictName' => 'Quận Bình Thạnh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 44, 'DistrictName' => 'Quận Gò Vấp', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 45, 'DistrictName' => 'Quận Phú Nhuận', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 46, 'DistrictName' => 'Quận Tân Bình', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 47, 'DistrictName' => 'Quận Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 48, 'DistrictName' => 'Quận Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 49, 'DistrictName' => 'Huyện Hóc Môn', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 50, 'DistrictName' => 'Huyện Củ Chi', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 51, 'DistrictName' => 'Huyện Nhà Bè', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 52, 'DistrictName' => 'Huyện Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 53, 'DistrictName' => 'Huyện Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 54, 'DistrictName' => 'Đồ Sơn', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 55, 'DistrictName' => 'Dương Kinh', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 56, 'DistrictName' => 'Hải An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 57, 'DistrictName' => 'Hồng Bàng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 58, 'DistrictName' => ' Kiến An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 59, 'DistrictName' => 'Lê Chân', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 60, 'DistrictName' => 'Ngô Quyền', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 61, 'DistrictName' => 'An Dương', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
             ['DistrictID' => 62, 'DistrictName' => 'An Lão', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 63, 'DistrictName' => 'Bạch Long Vĩ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 64, 'DistrictName' => 'Cát Hải', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 65, 'DistrictName' => 'Kiến Thuỵ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 66, 'DistrictName' => 'Thủy Nguyên', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 67, 'DistrictName' => 'Tiên Lãng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 68, 'DistrictName' => ' Vĩnh Bảo', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 69, 'DistrictName' => 'Quận Ninh Kiều', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 70, 'DistrictName' => 'Quận Bình Thuỷ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 71, 'DistrictName' => 'Quận Thốt Nốt', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 72, 'DistrictName' => 'Quận Cái Răng', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 73, 'DistrictName' => 'Quận Ô Môn', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 74, 'DistrictName' => 'Huyện Cờ Đỏ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 75, 'DistrictName' => 'Huyện Phong Điền', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 76, 'DistrictName' => 'Huyện Thới Lai', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 77, 'DistrictName' => 'Huyện Vĩnh Thạnh', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 78, 'DistrictName' => 'Hải Châu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 79, 'DistrictName' => 'Cẩm Lệ', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 80, 'DistrictName' => 'Thanh Khê', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 81, 'DistrictName' => 'Liên Chiểu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 82, 'DistrictName' => 'Ngũ Hành Sơn', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 83, 'DistrictName' => 'Sơn Trà', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 84, 'DistrictName' => 'Hòa Vang', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 85, 'DistrictName' => 'Hoàng Sa', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 86, 'DistrictName' => 'Thành phố Hà Giang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 87, 'DistrictName' => 'Huyện Bắc Mê', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 88, 'DistrictName' => 'Huyện Bắc Quang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 89, 'DistrictName' => 'Huyện Đồng Văn', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 90, 'DistrictName' => 'Huyện Hoàng Su Phì', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 91, 'DistrictName' => 'Huyện Mèo Vạc', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 92, 'DistrictName' => 'Huyện Quản Bạ', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 93, 'DistrictName' => 'Huyện Quang Bình', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 94, 'DistrictName' => 'Huyện Vị Xuyên', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 95, 'DistrictName' => 'Huyện Xín Mần', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 96, 'DistrictName' => 'Huyện Yên Minh', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 97, 'DistrictName' => 'Thành phố Cao Bằng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 98, 'DistrictName' => 'Huyện Bảo Lâm', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 99, 'DistrictName' => 'Huyện Bảo Lạc', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 100, 'DistrictName' => 'Huyện Hà Quảng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 101, 'DistrictName' => 'Huyện Trùng Khánh', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 102, 'DistrictName' => 'Huyện Hạ Lang', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 103, 'DistrictName' => 'Huyện Quảng Hòa', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 104, 'DistrictName' => 'Huyện Hoà An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 105, 'DistrictName' => 'Huyện Nguyên Bình', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 106, 'DistrictName' => 'Huyện Thạch An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 107, 'DistrictName' => 'Thành phố Lai Châu', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 108, 'DistrictName' => 'Huyện Tam Đường', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 109, 'DistrictName' => 'Huyện Mường Tè', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 110, 'DistrictName' => 'Huyện Sìn Hồ', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 111, 'DistrictName' => 'Huyện Phong Thổ', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 112, 'DistrictName' => 'Huyện Than Uyên', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 113, 'DistrictName' => 'Huyện Tân Uyên', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 114, 'DistrictName' => 'Huyện Nậm Nhùn', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 115, 'DistrictName' => 'Thành phố Lào Cai', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 116, 'DistrictName' => 'Huyện Bát Xát', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 117, 'DistrictName' => 'Huyện Mường Khương', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 118, 'DistrictName' => 'Huyện Si Ma Cai', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 119, 'DistrictName' => 'Huyện Bắc Hà', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 120, 'DistrictName' => 'Huyện Bảo Thắng', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 121, 'DistrictName' => 'Huyện Bảo Yên', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 122, 'DistrictName' => 'Thị xã Sa Pa', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 123, 'DistrictName' => 'Huyện Văn Bàn', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 124, 'DistrictName' => 'Thành phố Tuyên Quang', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 125, 'DistrictName' => 'Huyện Lâm Bình', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 126, 'DistrictName' => 'Huyện Na Hang', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 127, 'DistrictName' => 'Huyện Chiêm Hóa', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 128, 'DistrictName' => 'Huyện Hàm Yên', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 129, 'DistrictName' => 'Huyện Yên Sơn', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 130, 'DistrictName' => 'Huyện Sơn Dương', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 131, 'DistrictName' => 'Thành phố Lạng Sơn', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 132, 'DistrictName' => 'Huyện Tràng Định', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 133, 'DistrictName' => 'Huyện Bình Gia', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 134, 'DistrictName' => 'Huyện Văn Lãng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 135, 'DistrictName' => 'Huyện Cao Lộc', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 136, 'DistrictName' => 'Huyện Văn Quan', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 137, 'DistrictName' => 'Huyện Bắc Sơn', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 138, 'DistrictName' => 'Huyện Hữu Lũng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 139, 'DistrictName' => 'Huyện Chi Lăng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 140, 'DistrictName' => 'Huyện Lộc Bình', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 141, 'DistrictName' => 'Huyện Đình Lập', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 142, 'DistrictName' => 'Thành Phố Bắc Kạn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 143, 'DistrictName' => 'Huyện Pác Nặm', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 144, 'DistrictName' => 'Huyện Ba Bể', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 145, 'DistrictName' => 'Huyện Ngân Sơn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 146, 'DistrictName' => 'Huyện Bạch Thông', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 147, 'DistrictName' => 'Huyện Chợ Đồn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 148, 'DistrictName' => 'Huyện Chợ Mới', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 149, 'DistrictName' => 'Huyện Na Rì', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 150, 'DistrictName' => 'Thành phố Thái Nguyên', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 151, 'DistrictName' => 'Thành phố Sông Công', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 152, 'DistrictName' => 'Huyện Định Hóa', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 153, 'DistrictName' => 'Huyện Phú Lương', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 154, 'DistrictName' => 'Huyện Đồng Hỷ', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 155, 'DistrictName' => 'Huyện Võ Nhai', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 156, 'DistrictName' => 'Huyện Đại Từ', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 157, 'DistrictName' => 'Thành phố Phổ Yên', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 158, 'DistrictName' => 'Huyện Phú Bình', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 159, 'DistrictName' => 'Thành phố Yên Bái', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 160, 'DistrictName' => 'Thị xã Nghĩa Lộ', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 161, 'DistrictName' => 'Huyện Lục Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 162, 'DistrictName' => 'Huyện Văn Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 163, 'DistrictName' => 'Huyện Mù Căng Chải', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 164, 'DistrictName' => 'Huyện Trấn Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 165, 'DistrictName' => 'Huyện Trạm Tấu', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 166, 'DistrictName' => 'Huyện Văn Chấn', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 167, 'DistrictName' => 'Huyện Yên Bình', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 168, 'DistrictName' => 'Thành phố Sơn La', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 169, 'DistrictName' => 'Huyện Quỳnh Nhai', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 170, 'DistrictName' => 'Huyện Thuận Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 171, 'DistrictName' => 'Huyện Mường La', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 172, 'DistrictName' => 'Huyện Bắc Yên', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 173, 'DistrictName' => 'Huyện Phù Yên', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 174, 'DistrictName' => 'Huyện Mộc Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 175, 'DistrictName' => 'Huyện Yên Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 176, 'DistrictName' => 'Huyện Mai Sơn', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 177, 'DistrictName' => 'Huyện Sông Mã', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 178, 'DistrictName' => 'Huyện Sốp Cộp', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 179, 'DistrictName' => 'Huyện Vân Hồ', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 180, 'DistrictName' => 'Thành phố Việt Trì', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 181, 'DistrictName' => 'Thị xã Phú Thọ', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 182, 'DistrictName' => 'Huyện Đoan Hùng', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 183, 'DistrictName' => 'Huyện Hạ Hoà', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 184, 'DistrictName' => 'Huyện Thanh Ba', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 185, 'DistrictName' => 'Huyện Phù Ninh', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 186, 'DistrictName' => 'Huyện Yên Lập', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 187, 'DistrictName' => 'Huyện Cẩm Khê', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 188, 'DistrictName' => 'Huyện Tam Nông', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 189, 'DistrictName' => 'Huyện Lâm Thao', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 190, 'DistrictName' => 'Huyện Thanh Sơn', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 191, 'DistrictName' => 'Huyện Thanh Thuỷ', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 192, 'DistrictName' => 'Huyện Tân Sơn', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 193, 'DistrictName' => 'Thành phố Vĩnh Yên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 194, 'DistrictName' => 'Thành phố Phúc Yên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 195, 'DistrictName' => 'Huyện Lập Thạch', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 196, 'DistrictName' => 'Huyện Tam Dương', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 197, 'DistrictName' => 'Huyện Tam Đảo', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 198, 'DistrictName' => 'Huyện Bình Xuyên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 199, 'DistrictName' => 'Huyện Yên Lạc', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 200, 'DistrictName' => 'Huyện Vĩnh Tường', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 201, 'DistrictName' => 'Huyện Sông Lô', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 202, 'DistrictName' => 'Thành phố Hạ Long', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 203, 'DistrictName' => 'Thành phố Móng Cái', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 204, 'DistrictName' => 'Thành phố Cẩm Phả', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 205, 'DistrictName' => 'Thành phố Uông Bí', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 206, 'DistrictName' => 'Huyện Bình Liêu', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 207, 'DistrictName' => 'Huyện Tiên Yên', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 208, 'DistrictName' => 'Huyện Đầm Hà', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 209, 'DistrictName' => 'Huyện Hải Hà', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 210, 'DistrictName' => 'Huyện Ba Chẽ', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 211, 'DistrictName' => 'Huyện Vân Đồn', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 212, 'DistrictName' => 'Thị xã Đông Triều', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 213, 'DistrictName' => 'Thị xã Quảng Yên', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 214, 'DistrictName' => 'Huyện Cô Tô', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 215, 'DistrictName' => 'Thành phố Bắc Giang', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 216, 'DistrictName' => 'Huyện Yên Thế', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 217, 'DistrictName' => 'Huyện Tân Yên', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 218, 'DistrictName' => 'Huyện Lạng Giang', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 219, 'DistrictName' => 'Huyện Lục Nam', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 220, 'DistrictName' => 'Huyện Lục Ngạn', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 221, 'DistrictName' => 'Huyện Sơn Động', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 222, 'DistrictName' => 'Huyện Yên Dũng', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 223, 'DistrictName' => 'Huyện Việt Yên', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 224, 'DistrictName' => 'Huyện Hiệp Hòa', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 225, 'DistrictName' => 'Thành phố Bắc Ninh', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 226, 'DistrictName' => 'Huyện Yên Phong', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 227, 'DistrictName' => 'Huyện Quế Võ', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 228, 'DistrictName' => 'Huyện Tiên Du', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 229, 'DistrictName' => 'Thành phố Từ Sơn', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 230, 'DistrictName' => 'Huyện Thuận Thành', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 231, 'DistrictName' => 'Huyện Gia Bình', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 232, 'DistrictName' => 'Huyện Lương Tài', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 233, 'DistrictName' => 'Thành phố Hải Dương', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 234, 'DistrictName' => 'Thành phố Chí Linh', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 235, 'DistrictName' => 'Thị xã Kinh Môn', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 236, 'DistrictName' => 'Huyện Kim Thành', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 237, 'DistrictName' => 'Huyện Thanh Hà', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 238, 'DistrictName' => 'Huyện Cẩm Giàng', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 239, 'DistrictName' => 'Huyện Bình Giang', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 240, 'DistrictName' => 'Huyện Gia Lộc', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 241, 'DistrictName' => 'Huyện Tứ Kỳ', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 242, 'DistrictName' => 'Huyện Ninh Giang', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 243, 'DistrictName' => 'Huyện Nam Sách', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 244, 'DistrictName' => 'Huyện Thanh Miện', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 245, 'DistrictName' => 'Thành phố Hưng Yên', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 246, 'DistrictName' => 'Huyện Văn Lâm', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 247, 'DistrictName' => 'Huyện Văn Giang', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 248, 'DistrictName' => 'Huyện Yên Mỹ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 249, 'DistrictName' => 'Thị xã Mỹ Hào', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 250, 'DistrictName' => 'Huyện Ân Thi', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 251, 'DistrictName' => 'Huyện Khoái Châu', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 252, 'DistrictName' => 'Huyện Kim Động', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 253, 'DistrictName' => 'Huyện Tiên Lữ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 254, 'DistrictName' => 'Huyện Phù Cừ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 255, 'DistrictName' => 'Thành phố Thái Bình', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 256, 'DistrictName' => 'Huyện Quỳnh Phụ', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 257, 'DistrictName' => 'Huyện Hưng Hà', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 258, 'DistrictName' => 'Huyện Đông Hưng', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 259, 'DistrictName' => 'Huyện Thái Thụy', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 260, 'DistrictName' => 'Huyện Tiền Hải', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 261, 'DistrictName' => 'Huyện Kiến Xương', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 262, 'DistrictName' => 'Huyện Vũ Thư', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 263, 'DistrictName' => 'Thành phố Phủ Lý', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 264, 'DistrictName' => 'Thị xã Duy Tiên', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 265, 'DistrictName' => 'Huyện Kim Bảng', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 266, 'DistrictName' => 'Huyện Thanh Liêm', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 267, 'DistrictName' => 'Huyện Bình Lục', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 268, 'DistrictName' => 'Huyện Lý Nhân', 'CityID' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 269, 'DistrictName' => 'Thành phố Nam Định', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 270, 'DistrictName' => 'Huyện Mỹ Lộc', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 271, 'DistrictName' => 'Huyện Vụ Bản', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 272, 'DistrictName' => 'Huyện Ý Yên', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 273, 'DistrictName' => 'Huyện Nghĩa Hưng', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 274, 'DistrictName' => 'Huyện Nam Trực', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 275, 'DistrictName' => 'Huyện Trực Ninh', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 276, 'DistrictName' => 'Huyện Xuân Trường', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 277, 'DistrictName' => 'Huyện Giao Thủy', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 278, 'DistrictName' => 'Huyện Hải Hậu', 'CityID' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 279, 'DistrictName' => 'Thành phố Ninh Bình', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 280, 'DistrictName' => 'Thành phố Tam Điệp', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 281, 'DistrictName' => 'Huyện Nho Quan', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 282, 'DistrictName' => 'Huyện Gia Viễn', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 283, 'DistrictName' => 'Huyện Hoa Lư', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 284, 'DistrictName' => 'Huyện Yên Khánh', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 285, 'DistrictName' => 'Huyện Kim Sơn', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 286, 'DistrictName' => 'Huyện Yên Mô', 'CityID' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 287, 'DistrictName' => 'Thành phố Thanh Hóa', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 288, 'DistrictName' => 'Thị xã Bỉm Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 289, 'DistrictName' => 'Thành phố Sầm Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 290, 'DistrictName' => 'Huyện Mường Lát', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 291, 'DistrictName' => 'Huyện Quan Hóa', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 292, 'DistrictName' => 'Huyện Bá Thước', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 293, 'DistrictName' => 'Huyện Quan Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 294, 'DistrictName' => 'Huyện Lang Chánh', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 295, 'DistrictName' => 'Huyện Ngọc Lặc', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 296, 'DistrictName' => 'Huyện Cẩm Thủy', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 297, 'DistrictName' => 'Huyện Thạch Thành', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 298, 'DistrictName' => 'Huyện Hà Trung', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 299, 'DistrictName' => 'Huyện Vĩnh Lộc', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 300, 'DistrictName' => 'Huyện Yên Định', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 301, 'DistrictName' => 'Huyện Thọ Xuân', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 302, 'DistrictName' => 'Huyện Thường Xuân', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 303, 'DistrictName' => 'Huyện Triệu Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 304, 'DistrictName' => 'Huyện Thiệu Hóa', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 305, 'DistrictName' => 'Huyện Hoằng Hóa', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 306, 'DistrictName' => 'Huyện Hậu Lộc', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 307, 'DistrictName' => 'Huyện Nga Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 308, 'DistrictName' => 'Huyện Như Xuân', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 309, 'DistrictName' => 'Huyện Như Thanh', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 310, 'DistrictName' => 'Huyện Nông Cống', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 311, 'DistrictName' => 'Huyện Đông Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 312, 'DistrictName' => 'Huyện Quảng Xương', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 313, 'DistrictName' => 'Thị xã Nghi Sơn', 'CityID' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 314, 'DistrictName' => 'Thành phố Vinh', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 315, 'DistrictName' => 'Thị xã Cửa Lò', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 316, 'DistrictName' => 'Thị xã Thái Hoà', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 317, 'DistrictName' => 'Huyện Quế Phong', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 318, 'DistrictName' => 'Huyện Quỳ Châu', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 319, 'DistrictName' => 'Huyện Kỳ Sơn', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 320, 'DistrictName' => 'Huyện Tương Dương', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 321, 'DistrictName' => 'Huyện Nghĩa Đàn', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 322, 'DistrictName' => 'Huyện Quỳ Hợp', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 323, 'DistrictName' => 'Huyện Quỳnh Lưu', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 324, 'DistrictName' => 'Huyện Con Cuông', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 325, 'DistrictName' => 'Huyện Tân Kỳ', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 326, 'DistrictName' => 'Huyện Anh Sơn', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 327, 'DistrictName' => 'Huyện Diễn Châu', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 328, 'DistrictName' => 'Huyện Yên Thành', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 329, 'DistrictName' => 'Huyện Đô Lương', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 330, 'DistrictName' => 'Huyện Thanh Chương', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 331, 'DistrictName' => 'Huyện Nghi Lộc', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 332, 'DistrictName' => 'Huyện Nam Đàn', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 333, 'DistrictName' => 'Huyện Hưng Nguyên', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 334, 'DistrictName' => 'Thị xã Hoàng Mai', 'CityID' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 335, 'DistrictName' => 'Thành phố Hà Tĩnh', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 336, 'DistrictName' => 'Thị xã Hồng Lĩnh', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 337, 'DistrictName' => 'Huyện Hương Sơn', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 338, 'DistrictName' => 'Huyện Đức Thọ', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 339, 'DistrictName' => 'Huyện Vũ Quang', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 340, 'DistrictName' => 'Huyện Nghi Xuân', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 341, 'DistrictName' => 'Huyện Can Lộc', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 342, 'DistrictName' => 'Huyện Hương Khê', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 343, 'DistrictName' => 'Huyện Thạch Hà', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 344, 'DistrictName' => 'Huyện Cẩm Xuyên', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 345, 'DistrictName' => 'Huyện Kỳ Anh', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 346, 'DistrictName' => 'Huyện Lộc Hà', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 347, 'DistrictName' => 'Thị xã Kỳ Anh', 'CityID' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 348, 'DistrictName' => 'Thành Phố Đồng Hới', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 349, 'DistrictName' => 'Huyện Minh Hóa', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 350, 'DistrictName' => 'Huyện Tuyên Hóa', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 351, 'DistrictName' => 'Huyện Quảng Trạch', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 352, 'DistrictName' => 'Huyện Bố Trạch', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 353, 'DistrictName' => 'Huyện Quảng Ninh', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 354, 'DistrictName' => 'Huyện Lệ Thủy', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 355, 'DistrictName' => 'Thị xã Ba Đồn', 'CityID' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 356, 'DistrictName' => 'Thành phố Đông Hà', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 357, 'DistrictName' => 'Thị xã Quảng Trị', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 358, 'DistrictName' => 'Huyện Vĩnh Linh', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 359, 'DistrictName' => 'Huyện Hướng Hóa', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 360, 'DistrictName' => 'Huyện Gio Linh', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 361, 'DistrictName' => 'Huyện Đa Krông', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 362, 'DistrictName' => 'Huyện Cam Lộ', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 363, 'DistrictName' => 'Huyện Triệu Phong', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 364, 'DistrictName' => 'Huyện Hải Lăng', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 365, 'DistrictName' => 'Huyện Cồn Cỏ', 'CityID' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 366, 'DistrictName' => 'Thành phố Huế', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 367, 'DistrictName' => 'Thị xã Hương Thủy', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 368, 'DistrictName' => 'Thị xã Hương Trà', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 369, 'DistrictName' => 'Huyện A Lưới', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 370, 'DistrictName' => 'Huyện Nam Đông', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 371, 'DistrictName' => 'Huyện Phong Điền', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 372, 'DistrictName' => 'Huyện Phú Lộc', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 373, 'DistrictName' => 'Huyện Phú Vang', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 374, 'DistrictName' => 'Huyện Quảng Điền', 'CityID' => 32, 'created_at' => now(), 'updated_at' => now()],
            //----33-----
            ['DistrictID' => 375, 'DistrictName' => 'Thành phố Hòa Bình', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 376, 'DistrictName' => 'Huyện Đà Bắc', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 377, 'DistrictName' => 'Huyện Lương Sơn', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 378, 'DistrictName' => 'Huyện Kim Bôi', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 379, 'DistrictName' => 'Huyện Cao Phong', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 380, 'DistrictName' => 'Huyện Tân Lạc', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 381, 'DistrictName' => 'Huyện Mai Châu', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 382, 'DistrictName' => 'Huyện Lạc Sơn', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 383, 'DistrictName' => 'Huyện Yên Thủy', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 384, 'DistrictName' => 'Huyện Lạc Thủy', 'CityID' => 33, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 385, 'DistrictName' => 'Thành phố Tam Kỳ', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 386, 'DistrictName' => 'Thành phố Hội An', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 387, 'DistrictName' => 'Huyện Tây Giang', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 388, 'DistrictName' => 'Huyện Đông Giang', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 389, 'DistrictName' => 'Huyện Đại Lộc', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 390, 'DistrictName' => 'Thị xã Điện Bàn', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 391, 'DistrictName' => 'Huyện Duy Xuyên', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 392, 'DistrictName' => 'Huyện Quế Sơn', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 393, 'DistrictName' => 'Huyện Nam Giang', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 394, 'DistrictName' => 'Huyện Phước Sơn', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 395, 'DistrictName' => 'Huyện Hiệp Đức', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 396, 'DistrictName' => 'Huyện Thăng Bình', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 397, 'DistrictName' => 'Huyện Tiên Phước', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 398, 'DistrictName' => 'Huyện Bắc Trà My', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 399, 'DistrictName' => 'Huyện Nam Trà My', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 400, 'DistrictName' => 'Huyện Núi Thành', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 401, 'DistrictName' => 'Huyện Phú Ninh', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 402, 'DistrictName' => 'Huyện Nông Sơn', 'CityID' => 34, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 403, 'DistrictName' => 'Thành phố Quảng Ngãi', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 404, 'DistrictName' => 'Huyện Bình Sơn', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 405, 'DistrictName' => 'Huyện Trà Bồng', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 406, 'DistrictName' => 'Huyện Sơn Tịnh', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 407, 'DistrictName' => 'Huyện Tư Nghĩa', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 408, 'DistrictName' => 'Huyện Sơn Hà', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 409, 'DistrictName' => 'Huyện Sơn Tây', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 410, 'DistrictName' => 'Huyện Minh Long', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 411, 'DistrictName' => 'Huyện Nghĩa Hành', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 412, 'DistrictName' => 'Huyện Mộ Đức', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 413, 'DistrictName' => 'Thị xã Đức Phổ', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 414, 'DistrictName' => 'Huyện Ba Tơ', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 415, 'DistrictName' => 'Huyện Lý Sơn', 'CityID' => 35, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 416, 'DistrictName' => 'Thành phố Quy Nhơn', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 417, 'DistrictName' => 'Huyện An Lão', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 418, 'DistrictName' => 'Thị xã Hoài Nhơn', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 419, 'DistrictName' => 'Huyện Hoài Ân', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 420, 'DistrictName' => 'Huyện Phù Mỹ', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 421, 'DistrictName' => 'Huyện Vĩnh Thạnh', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 422, 'DistrictName' => 'Huyện Tây Sơn', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 423, 'DistrictName' => 'Huyện Phù Cát', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 424, 'DistrictName' => 'Thị xã An Nhơn', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 425, 'DistrictName' => 'Huyện Tuy Phước', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 426, 'DistrictName' => 'Huyện Vân Canh', 'CityID' => 36, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 427, 'DistrictName' => 'Thành phố Tuy Hoà', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 428, 'DistrictName' => 'Thị xã Sông Cầu', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 429, 'DistrictName' => 'Huyện Đồng Xuân', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 430, 'DistrictName' => 'Huyện Tuy An', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 431, 'DistrictName' => 'Huyện Sơn Hòa', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 432, 'DistrictName' => 'Huyện Sông Hinh', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 433, 'DistrictName' => 'Huyện Tây Hoà', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 434, 'DistrictName' => 'Huyện Phú Hoà', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 435, 'DistrictName' => 'Thị xã Đông Hòa', 'CityID' => 37, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 436, 'DistrictName' => 'Thành phố Nha Trang', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 437, 'DistrictName' => 'Thành phố Cam Ranh', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 438, 'DistrictName' => 'Huyện Cam Lâm', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 439, 'DistrictName' => 'Huyện Vạn Ninh', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 440, 'DistrictName' => 'Thị xã Ninh Hòa', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 441, 'DistrictName' => 'Huyện Khánh Vĩnh', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 442, 'DistrictName' => 'Huyện Diên Khánh', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 443, 'DistrictName' => 'Huyện Khánh Sơn', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 444, 'DistrictName' => 'Huyện Trường Sa', 'CityID' => 38, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 445, 'DistrictName' => 'Thành phố Nha Trang', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 446, 'DistrictName' => 'Thành phố Cam Ranh', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 447, 'DistrictName' => 'Huyện Cam Lâm', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 448, 'DistrictName' => 'Huyện Vạn Ninh', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 449, 'DistrictName' => 'Thị xã Ninh Hòa', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 450, 'DistrictName' => 'Huyện Khánh Vĩnh', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 451, 'DistrictName' => 'Huyện Diên Khánh', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 452, 'DistrictName' => 'Huyện Khánh Sơn', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 453, 'DistrictName' => 'Huyện Trường Sa', 'CityID' => 39, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 454, 'DistrictName' => 'Thành phố Phan Thiết', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 455, 'DistrictName' => 'Thị xã La Gi', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 456, 'DistrictName' => 'Huyện Tuy Phong', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 457, 'DistrictName' => 'Huyện Bắc Bình', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 458, 'DistrictName' => 'Huyện Hàm Thuận Bắc', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 459, 'DistrictName' => 'Huyện Hàm Thuận Nam', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 460, 'DistrictName' => 'Huyện Tánh Linh', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 461, 'DistrictName' => 'Huyện Đức Linh', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 462, 'DistrictName' => 'Huyện Hàm Tân', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 463, 'DistrictName' => 'Huyện Phú Quí', 'CityID' => 40, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 464, 'DistrictName' => 'Thành phố Kon Tum', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 465, 'DistrictName' => 'Huyện Đắk Glei', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 466, 'DistrictName' => 'Huyện Ngọc Hồi', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 467, 'DistrictName' => 'Huyện Đắk Tô', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 468, 'DistrictName' => 'Huyện Kon Plông', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 469, 'DistrictName' => 'Huyện Kon Rẫy', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 470, 'DistrictName' => 'Huyện Đắk Hà', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 471, 'DistrictName' => 'Huyện Sa Thầy', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 472, 'DistrictName' => 'Huyện Tu Mơ Rông', 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 473, 'DistrictName' => "Huyện Ia H' Drai", 'CityID' => 41, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 474, 'DistrictName' => 'Thành phố Pleiku', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 475, 'DistrictName' => 'Thị xã An Khê', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 476, 'DistrictName' => 'Thị xã Ayun Pa', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 477, 'DistrictName' => 'Huyện KBang', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 478, 'DistrictName' => 'Huyện Đăk Đoa', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 479, 'DistrictName' => 'Huyện Chư Păh', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 480, 'DistrictName' => 'Huyện Ia Grai', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 481, 'DistrictName' => 'Huyện Mang Yang', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 482, 'DistrictName' => 'Huyện Kông Chro', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 483, 'DistrictName' => 'Huyện Đức Cơ', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 484, 'DistrictName' => 'Huyện Chư Prông', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 485, 'DistrictName' => 'Huyện Chư Sê', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 486, 'DistrictName' => 'Huyện Đăk Pơ', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 487, 'DistrictName' => 'Huyện Ia Pa', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 488, 'DistrictName' => 'Huyện Krông Pa', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 489, 'DistrictName' => 'Huyện Phú Thiện', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 490, 'DistrictName' => 'Huyện Chư Pưh', 'CityID' => 42, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 491, 'DistrictName' => 'Thành phố Buôn Ma Thuột', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 492, 'DistrictName' => 'Thị Xã Buôn Hồ', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 493, 'DistrictName' => "Huyện Ea H'leo", 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 494, 'DistrictName' => 'Huyện Ea Súp', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 495, 'DistrictName' => 'Huyện Buôn Đôn', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 496, 'DistrictName' => "Huyện Cư M'gar", 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 497, 'DistrictName' => 'Huyện Krông Búk', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 498, 'DistrictName' => 'Huyện Krông Năng', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 499, 'DistrictName' => 'Huyện Ea Kar', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 500, 'DistrictName' => "Huyện M'Đrắk", 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 501, 'DistrictName' => 'Huyện Krông Bông', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 502, 'DistrictName' => 'Huyện Krông Pắc', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 503, 'DistrictName' => 'Huyện Krông A Na', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 504, 'DistrictName' => 'Huyện Lắk', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 505, 'DistrictName' => 'Huyện Cư Kuin', 'CityID' => 43, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 506, 'DistrictName' => 'Thành phố Gia Nghĩa', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 507, 'DistrictName' => 'Huyện Đăk Glong', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 508, 'DistrictName' => 'Huyện Cư Jút', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 509, 'DistrictName' => 'Huyện Đắk Mil', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 510, 'DistrictName' => 'Huyện Krông Nô', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 511, 'DistrictName' => 'Huyện Đắk Song', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 512, 'DistrictName' => "Huyện Đắk R'Lấp", 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 513, 'DistrictName' => 'Huyện Tuy Đức', 'CityID' => 44, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 514, 'DistrictName' => 'Thành phố Đà Lạt', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 515, 'DistrictName' => 'Thành phố Bảo Lộc', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 516, 'DistrictName' => 'Huyện Đam Rông', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 517, 'DistrictName' => 'Huyện Lạc Dương', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 518, 'DistrictName' => 'Huyện Lâm Hà', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 519, 'DistrictName' => 'Huyện Đơn Dương', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 520, 'DistrictName' => 'Huyện Đức Trọng', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 521, 'DistrictName' => 'Huyện Di Linh', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 522, 'DistrictName' => 'Huyện Bảo Lâm', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 523, 'DistrictName' => 'Huyện Đạ Huoai', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 524, 'DistrictName' => 'Huyện Đạ Tẻh', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 525, 'DistrictName' => 'Huyện Cát Tiên', 'CityID' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 526, 'DistrictName' => 'Thị xã Phước Long', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 527, 'DistrictName' => 'Thành phố Đồng Xoài', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 528, 'DistrictName' => 'Thị xã Bình Long', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 529, 'DistrictName' => 'Huyện Bù Gia Mập', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 530, 'DistrictName' => 'Huyện Lộc Ninh', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 531, 'DistrictName' => 'Huyện Bù Đốp', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 532, 'DistrictName' => 'Huyện Hớn Quản', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 533, 'DistrictName' => 'Huyện Đồng Phú', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 534, 'DistrictName' => 'Huyện Bù Đăng', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 535, 'DistrictName' => 'Huyện Chơn Thành', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 536, 'DistrictName' => 'Huyện Phú Riềng', 'CityID' => 46, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 537, 'DistrictName' => 'Thành phố Tây Ninh', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 538, 'DistrictName' => 'Huyện Tân Biên', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 539, 'DistrictName' => 'Huyện Tân Châu', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 540, 'DistrictName' => 'Huyện Dương Minh Châu', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 541, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 542, 'DistrictName' => 'Thị xã Hòa Thành', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 543, 'DistrictName' => 'Huyện Gò Dầu', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 544, 'DistrictName' => 'Huyện Bến Cầu', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 545, 'DistrictName' => 'Thị xã Trảng Bàng', 'CityID' => 47, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 546, 'DistrictName' => 'Thành phố Thủ Dầu Một', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 547, 'DistrictName' => 'Huyện Bàu Bàng', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 548, 'DistrictName' => 'Huyện Dầu Tiếng', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 549, 'DistrictName' => 'Thị xã Bến Cát', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 550, 'DistrictName' => 'Huyện Phú Giáo', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 551, 'DistrictName' => 'Thị xã Tân Uyên', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 552, 'DistrictName' => 'Thành phố Dĩ An', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 553, 'DistrictName' => 'Thành phố Thuận An', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 554, 'DistrictName' => 'Huyện Bắc Tân Uyên', 'CityID' => 48, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 555, 'DistrictName' => 'Thành phố Biên Hòa', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 556, 'DistrictName' => 'Thành phố Long Khánh', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 557, 'DistrictName' => 'Huyện Tân Phú', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 558, 'DistrictName' => 'Huyện Vĩnh Cửu', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 559, 'DistrictName' => 'Huyện Định Quán', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 560, 'DistrictName' => 'Huyện Trảng Bom', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 561, 'DistrictName' => 'Huyện Thống Nhất', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 562, 'DistrictName' => 'Huyện Cẩm Mỹ', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 563, 'DistrictName' => 'Huyện Long Thành', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 564, 'DistrictName' => 'Huyện Xuân Lộc', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 565, 'DistrictName' => 'Huyện Nhơn Trạch', 'CityID' => 49, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 566, 'DistrictName' => 'Thành phố Tân An', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 567, 'DistrictName' => 'Thị xã Kiến Tường', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 568, 'DistrictName' => 'Huyện Tân Hưng', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 569, 'DistrictName' => 'Huyện Vĩnh Hưng', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 570, 'DistrictName' => 'Huyện Mộc Hóa', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 571, 'DistrictName' => 'Huyện Tân Thạnh', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 572, 'DistrictName' => 'Huyện Thạnh Hóa', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 573, 'DistrictName' => 'Huyện Đức Huệ', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 574, 'DistrictName' => 'Huyện Đức Hòa', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 575, 'DistrictName' => 'Huyện Bến Lức', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 576, 'DistrictName' => 'Huyện Thủ Thừa', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 577, 'DistrictName' => 'Huyện Tân Trụ', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 578, 'DistrictName' => 'Huyện Cần Đước', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 579, 'DistrictName' => 'Huyện Cần Giuộc', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 580, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 581, 'DistrictName' => 'Thành phố Mỹ Tho', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 582, 'DistrictName' => 'Thị xã Gò Công', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 583, 'DistrictName' => 'Thị xã Cai Lậy', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 584, 'DistrictName' => 'Huyện Tân Phước', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 585, 'DistrictName' => 'Huyện Cái Bè', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 586, 'DistrictName' => 'Huyện Cai Lậy', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 587, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 588, 'DistrictName' => 'Huyện Chợ Gạo', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 589, 'DistrictName' => 'Huyện Gò Công Tây', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 590, 'DistrictName' => 'Huyện Gò Công Đông', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 591, 'DistrictName' => 'Huyện Tân Phú Đông', 'CityID' => 51, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 592, 'DistrictName' => 'Thành phố Bến Tre', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 593, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 594, 'DistrictName' => 'Huyện Chợ Lách', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 595, 'DistrictName' => 'Huyện Mỏ Cày Nam', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 596, 'DistrictName' => 'Huyện Giồng Trôm', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 597, 'DistrictName' => 'Huyện Bình Đại', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 598, 'DistrictName' => 'Huyện Ba Tri', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 599, 'DistrictName' => 'Huyện Thạnh Phú', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 600, 'DistrictName' => 'Huyện Mỏ Cày Bắc', 'CityID' => 52, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 601, 'DistrictName' => 'Thành phố Trà Vinh', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 602, 'DistrictName' => 'Huyện Càng Long', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 603, 'DistrictName' => 'Huyện Cầu Kè', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 604, 'DistrictName' => 'Huyện Tiểu Cần', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 605, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 606, 'DistrictName' => 'Huyện Cầu Ngang', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 607, 'DistrictName' => 'Huyện Trà Cú', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 608, 'DistrictName' => 'Huyện Duyên Hải', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 609, 'DistrictName' => 'Thị xã Duyên Hải', 'CityID' => 53, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 610, 'DistrictName' => 'Thành phố Vĩnh Long', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 611, 'DistrictName' => 'Huyện Long Hồ', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 612, 'DistrictName' => 'Huyện Mang Thít', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 613, 'DistrictName' => 'Huyện Vũng Liêm', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 614, 'DistrictName' => 'Huyện Tam Bình', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 615, 'DistrictName' => 'Thị xã Bình Minh', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 616, 'DistrictName' => 'Huyện Trà Ôn', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 617, 'DistrictName' => 'Huyện Bình Tân', 'CityID' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 618, 'DistrictName' => 'Thành phố Cao Lãnh', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 619, 'DistrictName' => 'Thành phố Sa Đéc', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 620, 'DistrictName' => 'Thành phố Hồng Ngự', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 621, 'DistrictName' => 'Huyện Tân Hồng', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 622, 'DistrictName' => 'Huyện Hồng Ngự', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 623, 'DistrictName' => 'Huyện Tam Nông', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 624, 'DistrictName' => 'Huyện Tháp Mười', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 625, 'DistrictName' => 'Huyện Cao Lãnh', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 626, 'DistrictName' => 'Huyện Thanh Bình', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 627, 'DistrictName' => 'Huyện Lấp Vò', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 628, 'DistrictName' => 'Huyện Lai Vung', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 629, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 55, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 630, 'DistrictName' => 'Thành phố Long Xuyên', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 631, 'DistrictName' => 'Thành phố Châu Đốc', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 632, 'DistrictName' => 'Huyện An Phú', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 633, 'DistrictName' => 'Thị xã Tân Châu', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 634, 'DistrictName' => 'Huyện Phú Tân', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 635, 'DistrictName' => 'Huyện Châu Phú', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 636, 'DistrictName' => 'Huyện Tịnh Biên', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 637, 'DistrictName' => 'Huyện Tri Tôn', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 638, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 639, 'DistrictName' => 'Huyện Chợ Mới', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 640, 'DistrictName' => 'Huyện Thoại Sơn', 'CityID' => 56, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 641, 'DistrictName' => 'Thành phố Rạch Giá', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 642, 'DistrictName' => 'Thành phố Hà Tiên', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 643, 'DistrictName' => 'Huyện Kiên Lương', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 644, 'DistrictName' => 'Huyện Hòn Đất', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 645, 'DistrictName' => 'Huyện Tân Hiệp', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 646, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 647, 'DistrictName' => 'Huyện Giồng Riềng', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 648, 'DistrictName' => 'Huyện Gò Quao', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 649, 'DistrictName' => 'Huyện An Biên', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 650, 'DistrictName' => 'Huyện An Minh', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 651, 'DistrictName' => 'Huyện Vĩnh Thuận', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 652, 'DistrictName' => 'Thành phố Phú Quốc', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 653, 'DistrictName' => 'Huyện Kiên Hải', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 654, 'DistrictName' => 'Huyện U Minh Thượng', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 655, 'DistrictName' => 'Huyện Giang Thành', 'CityID' => 57, 'created_at' => now(), 'updated_at' => now()],
            //----58------------------------
            ['DistrictID' => 656, 'DistrictName' => 'Thành phố Điện Biên Phủ', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 657, 'DistrictName' => 'Thị Xã Mường Lay', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 658, 'DistrictName' => 'Huyện Mường Nhé', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 659, 'DistrictName' => 'Huyện Mường Chà', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 660, 'DistrictName' => 'Huyện Tủa Chùa', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 661, 'DistrictName' => 'Huyện Tuần Giáo', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 662, 'DistrictName' => 'Huyện Điện Biên', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 663, 'DistrictName' => 'Huyện Điện Biên Đông', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 664, 'DistrictName' => 'Huyện Mường Ảng', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 665, 'DistrictName' => 'Huyện Nậm Pồ', 'CityID' => 58, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 666, 'DistrictName' => 'Thành phố Vị Thanh', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 667, 'DistrictName' => 'Thành phố Ngã Bảy', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 668, 'DistrictName' => 'Huyện Châu Thành A', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 669, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 670, 'DistrictName' => 'Huyện Phụng Hiệp', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 671, 'DistrictName' => 'Huyện Vị Thuỷ', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 672, 'DistrictName' => 'Huyện Long Mỹ', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 673, 'DistrictName' => 'Thị xã Long Mỹ', 'CityID' => 59, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 674, 'DistrictName' => 'Thành phố Sóc Trăng', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 675, 'DistrictName' => 'Huyện Châu Thành', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 676, 'DistrictName' => 'Huyện Kế Sách', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 677, 'DistrictName' => 'Huyện Mỹ Tú', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 678, 'DistrictName' => 'Huyện Cù Lao Dung', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 679, 'DistrictName' => 'Huyện Long Phú', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 680, 'DistrictName' => 'Huyện Mỹ Xuyên', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 681, 'DistrictName' => 'Thị xã Ngã Năm', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 682, 'DistrictName' => 'Huyện Thạnh Trị', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 683, 'DistrictName' => 'Thị xã Vĩnh Châu', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 684, 'DistrictName' => 'Huyện Trần Đề', 'CityID' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 685, 'DistrictName' => 'Thành phố Bạc Liêu', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 686, 'DistrictName' => 'Huyện Hồng Dân', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 687, 'DistrictName' => 'Huyện Phước Long', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 688, 'DistrictName' => 'Huyện Vĩnh Lợi', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 689, 'DistrictName' => 'Thị xã Giá Rai', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 690, 'DistrictName' => 'Huyện Đông Hải', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 691, 'DistrictName' => 'Huyện Hoà Bình', 'CityID' => 61, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 692, 'DistrictName' => 'Thành phố Cà Mau', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 693, 'DistrictName' => 'Huyện U Minh', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 694, 'DistrictName' => 'Huyện Thới Bình', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 695, 'DistrictName' => 'Huyện Trần Văn Thời', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 696, 'DistrictName' => 'Huyện Cái Nước', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 697, 'DistrictName' => 'Huyện Đầm Dơi', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 698, 'DistrictName' => 'Huyện Năm Căn', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 699, 'DistrictName' => 'Huyện Phú Tân', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 700, 'DistrictName' => 'Huyện Ngọc Hiển', 'CityID' => 62, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 701, 'DistrictName' => 'Thành phố Vũng Tàu', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 702, 'DistrictName' => 'Thành phố Bà Rịa', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 703, 'DistrictName' => 'Huyện Châu Đức', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 704, 'DistrictName' => 'Huyện Xuyên Mộc', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 705, 'DistrictName' => 'Huyện Long Điền', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 706, 'DistrictName' => 'Huyện Đất Đỏ', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 707, 'DistrictName' => 'Thị xã Phú Mỹ', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 708, 'DistrictName' => 'Huyện Côn Đảo', 'CityID' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 709, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
        ];
        DB::table('districts')->insert($districts);
    }
}