<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $Districts = [
            ['DistrictID' => 1, 'DistrictName' => 'Ba Đình', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 2, 'DistrictName' => 'Hoàn Kiếm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 3, 'DistrictName' => 'Hai Bà Trưng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 4, 'DistrictName' => 'Đống Đa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 5, 'DistrictName' => 'Tây Hồ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 6, 'DistrictName' => 'Cầu Giấy', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 7, 'DistrictName' => 'Thanh Xuân', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 8, 'DistrictName' => 'Hoàng Mai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 9, 'DistrictName' => 'Long Biên', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 10, 'DistrictName' => 'Nam Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 11, 'DistrictName' => 'Bắc Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 12, 'DistrictName' => 'Hà Đông', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 13, 'DistrictName' => 'Sơn Tây', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 13, 'DistrictName' => 'Sóc Sơn', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 15, 'DistrictName' => 'Đông Anh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 16, 'DistrictName' => 'Gia Lâm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 17, 'DistrictName' => 'Thanh Trì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 18, 'DistrictName' => 'Mê Linh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 19, 'DistrictName' => 'Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 20, 'DistrictName' => 'Ba Vì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 21, 'DistrictName' => 'Chương Mỹ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 22, 'DistrictName' => 'Đan Phượng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 23, 'DistrictName' => 'Hoài Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 24, 'DistrictName' => 'Quốc Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 25, 'DistrictName' => 'Thạch Thất', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 26, 'DistrictName' => 'Thanh Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 27, 'DistrictName' => 'Thường Tín', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 28, 'DistrictName' => 'Ứng Hòa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 29, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 29, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 30, 'DistrictName' => 'Phúc Thọ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],         
            ['DistrictID' => 31, 'DistrictName' => 'Thành Phố Tân Phú', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 32, 'DistrictName' => 'Quận 1', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 33, 'DistrictName' => 'Quận 3', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 34, 'DistrictName' => 'Quận 4', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 35, 'DistrictName' => 'Quận 5', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 36, 'DistrictName' => 'Quận 6', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 37, 'DistrictName' => 'Quận 7', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 38, 'DistrictName' => 'Quận 8', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 39, 'DistrictName' => 'Quận 10', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 40, 'DistrictName' => 'Quận 11', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 41, 'DistrictName' => 'Quận 12', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 42, 'DistrictName' => 'Quận Bình Tân', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 43, 'DistrictName' => 'Quận Bình Thạnh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 44, 'DistrictName' => 'Quận Gò Vấp', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 45, 'DistrictName' => 'Quận Phú Nhuận', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 46, 'DistrictName' => 'Quận Tân Bình', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 47, 'DistrictName' => 'Quận Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 48, 'DistrictName' => 'Quận Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 49, 'DistrictName' => 'Huyện Hóc Môn', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 50, 'DistrictName' => 'Huyện Củ Chi', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 51, 'DistrictName' => 'Huyện Nhà Bè', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 52, 'DistrictName' => 'Huyện Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 53, 'DistrictName' => 'Huyện Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 54, 'DistrictName' => 'Đồ Sơn', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 55, 'DistrictName' => 'Dương Kinh', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 56, 'DistrictName' => 'Hải An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 57, 'DistrictName' => 'Hồng Bàng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 58, 'DistrictName' => ' Kiến An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 59, 'DistrictName' => 'Lê Chân', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 60, 'DistrictName' => 'Ngô Quyền', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 61, 'DistrictName' => 'An Dương', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 62, 'DistrictName' => 'An Lão', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 63, 'DistrictName' => 'Bạch Long Vĩ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 64, 'DistrictName' => 'Cát Hải', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 65, 'DistrictName' => 'Kiến Thuỵ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 66, 'DistrictName' => 'Thủy Nguyên', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 67, 'DistrictName' => 'Tiên Lãng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 68, 'DistrictName' => ' Vĩnh Bảo', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 69, 'DistrictName' => 'Quận Ninh Kiều', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 70, 'DistrictName' => 'Quận Bình Thuỷ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 71, 'DistrictName' => 'Quận Thốt Nốt', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 72, 'DistrictName' => 'Quận Cái Răng', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 73, 'DistrictName' => 'Quận Ô Môn', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 74, 'DistrictName' => 'Huyện Cờ Đỏ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 75, 'DistrictName' => 'Huyện Phong Điền', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 76, 'DistrictName' => 'Huyện Thới Lai', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 77, 'DistrictName' => 'Huyện Vĩnh Thạnh', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 78, 'DistrictName' => 'Hải Châu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 79, 'DistrictName' => 'Cẩm Lệ', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 80, 'DistrictName' => 'Thanh Khê', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 81, 'DistrictName' => 'Liên Chiểu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 82, 'DistrictName' => 'Ngũ Hành Sơn', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 83, 'DistrictName' => 'Sơn Trà', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 84, 'DistrictName' => 'Hòa Vang', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 85, 'DistrictName' => 'Hoàng Sa', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 86, 'DistrictName' => 'Thành phố Hà Giang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 87, 'DistrictName' => 'Huyện Bắc Mê', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 88, 'DistrictName' => 'Huyện Bắc Quang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 89, 'DistrictName' => 'Huyện Đồng Văn', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 90, 'DistrictName' => 'Huyện Hoàng Su Phì', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 91, 'DistrictName' => 'Huyện Mèo Vạc', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 92, 'DistrictName' => 'Huyện Quản Bạ', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 93, 'DistrictName' => 'Huyện Quang Bình', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 94, 'DistrictName' => 'Huyện Vị Xuyên', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 95, 'DistrictName' => 'Huyện Xín Mần', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 96, 'DistrictName' => 'Huyện Yên Minh', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 97, 'DistrictName' => 'Thành phố Cao Bằng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 98, 'DistrictName' => 'Huyện Bảo Lâm', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 99, 'DistrictName' => 'Huyện Bảo Lạc', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 100, 'DistrictName' => 'Huyện Hà Quảng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 101, 'DistrictName' => 'Huyện Trùng Khánh', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 102, 'DistrictName' => 'Huyện Hạ Lang', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 103, 'DistrictName' => 'Huyện Quảng Hòa', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 104, 'DistrictName' => 'Huyện Hoà An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 105, 'DistrictName' => 'Huyện Nguyên Bình', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 106, 'DistrictName' => 'Huyện Thạch An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
        ];
    }
}