<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $Districts = [
            ['DistrictID' => 1, 'DistrictName' => 'Ba Đình', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 2, 'DistrictName' => 'Hoàn Kiếm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 3, 'DistrictName' => 'Hai Bà Trưng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 4, 'DistrictName' => 'Đống Đa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 5, 'DistrictName' => 'Tây Hồ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 6, 'DistrictName' => 'Cầu Giấy', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 7, 'DistrictName' => 'Thanh Xuân', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 8, 'DistrictName' => 'Hoàng Mai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 9, 'DistrictName' => 'Long Biên', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 10, 'DistrictName' => 'Nam Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 11, 'DistrictName' => 'Bắc Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 12, 'DistrictName' => 'Hà Đông', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 13, 'DistrictName' => 'Sơn Tây', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 13, 'DistrictName' => 'Sóc Sơn', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 15, 'DistrictName' => 'Đông Anh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 16, 'DistrictName' => 'Gia Lâm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 17, 'DistrictName' => 'Thanh Trì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 18, 'DistrictName' => 'Mê Linh', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 19, 'DistrictName' => 'Từ Liêm', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 20, 'DistrictName' => 'Ba Vì', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 21, 'DistrictName' => 'Chương Mỹ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 22, 'DistrictName' => 'Đan Phượng', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 23, 'DistrictName' => 'Hoài Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 24, 'DistrictName' => 'Quốc Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 25, 'DistrictName' => 'Thạch Thất', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 26, 'DistrictName' => 'Thanh Oai', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 27, 'DistrictName' => 'Thường Tín', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 28, 'DistrictName' => 'Ứng Hòa', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 29, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 29, 'DistrictName' => 'Mỹ Đức', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 30, 'DistrictName' => 'Phúc Thọ', 'CityID' => 1, 'created_at' => now(), 'updated_at' => now()],         
            ['DistrictID' => 31, 'DistrictName' => 'Thành Phố Tân Phú', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['DistrictID' => 32, 'DistrictName' => 'Quận 1', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 33, 'DistrictName' => 'Quận 3', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 34, 'DistrictName' => 'Quận 4', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 35, 'DistrictName' => 'Quận 5', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 36, 'DistrictName' => 'Quận 6', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 37, 'DistrictName' => 'Quận 7', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 38, 'DistrictName' => 'Quận 8', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 39, 'DistrictName' => 'Quận 10', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 40, 'DistrictName' => 'Quận 11', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 41, 'DistrictName' => 'Quận 12', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 42, 'DistrictName' => 'Quận Bình Tân', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 43, 'DistrictName' => 'Quận Bình Thạnh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 44, 'DistrictName' => 'Quận Gò Vấp', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 45, 'DistrictName' => 'Quận Phú Nhuận', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 46, 'DistrictName' => 'Quận Tân Bình', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 47, 'DistrictName' => 'Quận Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 48, 'DistrictName' => 'Quận Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 49, 'DistrictName' => 'Huyện Hóc Môn', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 50, 'DistrictName' => 'Huyện Củ Chi', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 51, 'DistrictName' => 'Huyện Nhà Bè', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 52, 'DistrictName' => 'Huyện Bình Chánh', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 53, 'DistrictName' => 'Huyện Cần Giờ', 'CityID' => 2, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 54, 'DistrictName' => 'Đồ Sơn', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 55, 'DistrictName' => 'Dương Kinh', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 56, 'DistrictName' => 'Hải An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 57, 'DistrictName' => 'Hồng Bàng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 58, 'DistrictName' => ' Kiến An', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 59, 'DistrictName' => 'Lê Chân', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 60, 'DistrictName' => 'Ngô Quyền', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 61, 'DistrictName' => 'An Dương', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 62, 'DistrictName' => 'An Lão', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 63, 'DistrictName' => 'Bạch Long Vĩ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 64, 'DistrictName' => 'Cát Hải', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 65, 'DistrictName' => 'Kiến Thuỵ', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 66, 'DistrictName' => 'Thủy Nguyên', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 67, 'DistrictName' => 'Tiên Lãng', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 68, 'DistrictName' => ' Vĩnh Bảo', 'CityID' => 3, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 69, 'DistrictName' => 'Quận Ninh Kiều', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 70, 'DistrictName' => 'Quận Bình Thuỷ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 71, 'DistrictName' => 'Quận Thốt Nốt', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 72, 'DistrictName' => 'Quận Cái Răng', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 73, 'DistrictName' => 'Quận Ô Môn', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 74, 'DistrictName' => 'Huyện Cờ Đỏ', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 75, 'DistrictName' => 'Huyện Phong Điền', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 76, 'DistrictName' => 'Huyện Thới Lai', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 77, 'DistrictName' => 'Huyện Vĩnh Thạnh', 'CityID' => 4, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 78, 'DistrictName' => 'Hải Châu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 79, 'DistrictName' => 'Cẩm Lệ', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 80, 'DistrictName' => 'Thanh Khê', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 81, 'DistrictName' => 'Liên Chiểu', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 82, 'DistrictName' => 'Ngũ Hành Sơn', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 83, 'DistrictName' => 'Sơn Trà', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 84, 'DistrictName' => 'Hòa Vang', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 85, 'DistrictName' => 'Hoàng Sa', 'CityID' => 5, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 86, 'DistrictName' => 'Thành phố Hà Giang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 87, 'DistrictName' => 'Huyện Bắc Mê', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 88, 'DistrictName' => 'Huyện Bắc Quang', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 89, 'DistrictName' => 'Huyện Đồng Văn', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 90, 'DistrictName' => 'Huyện Hoàng Su Phì', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 91, 'DistrictName' => 'Huyện Mèo Vạc', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 92, 'DistrictName' => 'Huyện Quản Bạ', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 93, 'DistrictName' => 'Huyện Quang Bình', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 94, 'DistrictName' => 'Huyện Vị Xuyên', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 95, 'DistrictName' => 'Huyện Xín Mần', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 96, 'DistrictName' => 'Huyện Yên Minh', 'CityID' => 6, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 97, 'DistrictName' => 'Thành phố Cao Bằng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 98, 'DistrictName' => 'Huyện Bảo Lâm', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 99, 'DistrictName' => 'Huyện Bảo Lạc', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 100, 'DistrictName' => 'Huyện Hà Quảng', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 101, 'DistrictName' => 'Huyện Trùng Khánh', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 102, 'DistrictName' => 'Huyện Hạ Lang', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 103, 'DistrictName' => 'Huyện Quảng Hòa', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 104, 'DistrictName' => 'Huyện Hoà An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 105, 'DistrictName' => 'Huyện Nguyên Bình', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 106, 'DistrictName' => 'Huyện Thạch An', 'CityID' => 7, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 107, 'DistrictName' => 'Thành phố Lai Châu', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 108, 'DistrictName' => 'Huyện Tam Đường', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 109, 'DistrictName' => 'Huyện Mường Tè', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 110, 'DistrictName' => 'Huyện Sìn Hồ', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 111, 'DistrictName' => 'Huyện Phong Thổ', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 112, 'DistrictName' => 'Huyện Than Uyên', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 113, 'DistrictName' => 'Huyện Tân Uyên', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 114, 'DistrictName' => 'Huyện Nậm Nhùn', 'CityID' => 8, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 115, 'DistrictName' => 'Thành phố Lào Cai', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 116, 'DistrictName' => 'Huyện Bát Xát', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 117, 'DistrictName' => 'Huyện Mường Khương', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 118, 'DistrictName' => 'Huyện Si Ma Cai', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 119, 'DistrictName' => 'Huyện Bắc Hà', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 120, 'DistrictName' => 'Huyện Bảo Thắng', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 121, 'DistrictName' => 'Huyện Bảo Yên', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 122, 'DistrictName' => 'Thị xã Sa Pa', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 123, 'DistrictName' => 'Huyện Văn Bàn', 'CityID' => 9, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 124, 'DistrictName' => 'Thành phố Tuyên Quang', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 125, 'DistrictName' => 'Huyện Lâm Bình', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 126, 'DistrictName' => 'Huyện Na Hang', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 127, 'DistrictName' => 'Huyện Chiêm Hóa', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 128, 'DistrictName' => 'Huyện Hàm Yên', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 129, 'DistrictName' => 'Huyện Yên Sơn', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 130, 'DistrictName' => 'Huyện Sơn Dương', 'CityID' => 10, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 131, 'DistrictName' => 'Thành phố Lạng Sơn', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 132, 'DistrictName' => 'Huyện Tràng Định', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 133, 'DistrictName' => 'Huyện Bình Gia', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 134, 'DistrictName' => 'Huyện Văn Lãng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 135, 'DistrictName' => 'Huyện Cao Lộc', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 136, 'DistrictName' => 'Huyện Văn Quan', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 137, 'DistrictName' => 'Huyện Bắc Sơn', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 138, 'DistrictName' => 'Huyện Hữu Lũng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 139, 'DistrictName' => 'Huyện Chi Lăng', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 140, 'DistrictName' => 'Huyện Lộc Bình', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 141, 'DistrictName' => 'Huyện Đình Lập', 'CityID' => 11, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 142, 'DistrictName' => 'Thành Phố Bắc Kạn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 143, 'DistrictName' => 'Huyện Pác Nặm', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 144, 'DistrictName' => 'Huyện Ba Bể', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 145, 'DistrictName' => 'Huyện Ngân Sơn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 146, 'DistrictName' => 'Huyện Bạch Thông', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 147, 'DistrictName' => 'Huyện Chợ Đồn', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 148, 'DistrictName' => 'Huyện Chợ Mới', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 149, 'DistrictName' => 'Huyện Na Rì', 'CityID' => 12, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 150, 'DistrictName' => 'Thành phố Thái Nguyên', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 151, 'DistrictName' => 'Thành phố Sông Công', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 152, 'DistrictName' => 'Huyện Định Hóa', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 153, 'DistrictName' => 'Huyện Phú Lương', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 154, 'DistrictName' => 'Huyện Đồng Hỷ', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 155, 'DistrictName' => 'Huyện Võ Nhai', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 156, 'DistrictName' => 'Huyện Đại Từ', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 157, 'DistrictName' => 'Thành phố Phổ Yên', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 158, 'DistrictName' => 'Huyện Phú Bình', 'CityID' => 13, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 159, 'DistrictName' => 'Thành phố Yên Bái', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 160, 'DistrictName' => 'Thị xã Nghĩa Lộ', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 161, 'DistrictName' => 'Huyện Lục Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 162, 'DistrictName' => 'Huyện Văn Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 163, 'DistrictName' => 'Huyện Mù Căng Chải', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 164, 'DistrictName' => 'Huyện Trấn Yên', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 165, 'DistrictName' => 'Huyện Trạm Tấu', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 166, 'DistrictName' => 'Huyện Văn Chấn', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 167, 'DistrictName' => 'Huyện Yên Bình', 'CityID' => 14, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 168, 'DistrictName' => 'Thành phố Sơn La', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 169, 'DistrictName' => 'Huyện Quỳnh Nhai', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 170, 'DistrictName' => 'Huyện Thuận Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 171, 'DistrictName' => 'Huyện Mường La', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 172, 'DistrictName' => 'Huyện Bắc Yên', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 173, 'DistrictName' => 'Huyện Phù Yên', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 174, 'DistrictName' => 'Huyện Mộc Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 175, 'DistrictName' => 'Huyện Yên Châu', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 176, 'DistrictName' => 'Huyện Mai Sơn', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 177, 'DistrictName' => 'Huyện Sông Mã', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 178, 'DistrictName' => 'Huyện Sốp Cộp', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 179, 'DistrictName' => 'Huyện Vân Hồ', 'CityID' => 15, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 180, 'DistrictName' => 'Thành phố Việt Trì', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 181, 'DistrictName' => 'Thị xã Phú Thọ', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 182, 'DistrictName' => 'Huyện Đoan Hùng', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 183, 'DistrictName' => 'Huyện Hạ Hoà', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 184, 'DistrictName' => 'Huyện Thanh Ba', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 185, 'DistrictName' => 'Huyện Phù Ninh', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 186, 'DistrictName' => 'Huyện Yên Lập', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 187, 'DistrictName' => 'Huyện Cẩm Khê', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 188, 'DistrictName' => 'Huyện Tam Nông', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 189, 'DistrictName' => 'Huyện Lâm Thao', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 190, 'DistrictName' => 'Huyện Thanh Sơn', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 191, 'DistrictName' => 'Huyện Thanh Thuỷ', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 192, 'DistrictName' => 'Huyện Tân Sơn', 'CityID' => 16, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 193, 'DistrictName' => 'Thành phố Vĩnh Yên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 194, 'DistrictName' => 'Thành phố Phúc Yên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 195, 'DistrictName' => 'Huyện Lập Thạch', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 196, 'DistrictName' => 'Huyện Tam Dương', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 197, 'DistrictName' => 'Huyện Tam Đảo', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 198, 'DistrictName' => 'Huyện Bình Xuyên', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 199, 'DistrictName' => 'Huyện Yên Lạc', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 200, 'DistrictName' => 'Huyện Vĩnh Tường', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 201, 'DistrictName' => 'Huyện Sông Lô', 'CityID' => 17, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 202, 'DistrictName' => 'Thành phố Hạ Long', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 203, 'DistrictName' => 'Thành phố Móng Cái', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 204, 'DistrictName' => 'Thành phố Cẩm Phả', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 205, 'DistrictName' => 'Thành phố Uông Bí', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 206, 'DistrictName' => 'Huyện Bình Liêu', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 207, 'DistrictName' => 'Huyện Tiên Yên', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 208, 'DistrictName' => 'Huyện Đầm Hà', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 209, 'DistrictName' => 'Huyện Hải Hà', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 210, 'DistrictName' => 'Huyện Ba Chẽ', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 211, 'DistrictName' => 'Huyện Vân Đồn', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 212, 'DistrictName' => 'Thị xã Đông Triều', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 213, 'DistrictName' => 'Thị xã Quảng Yên', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 214, 'DistrictName' => 'Huyện Cô Tô', 'CityID' => 18, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 215, 'DistrictName' => 'Thành phố Bắc Giang', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 216, 'DistrictName' => 'Huyện Yên Thế', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 217, 'DistrictName' => 'Huyện Tân Yên', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 218, 'DistrictName' => 'Huyện Lạng Giang', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 219, 'DistrictName' => 'Huyện Lục Nam', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 220, 'DistrictName' => 'Huyện Lục Ngạn', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 221, 'DistrictName' => 'Huyện Sơn Động', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 222, 'DistrictName' => 'Huyện Yên Dũng', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 223, 'DistrictName' => 'Huyện Việt Yên', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 224, 'DistrictName' => 'Huyện Hiệp Hòa', 'CityID' => 19, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 225, 'DistrictName' => 'Thành phố Bắc Ninh', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 226, 'DistrictName' => 'Huyện Yên Phong', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 227, 'DistrictName' => 'Huyện Quế Võ', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 228, 'DistrictName' => 'Huyện Tiên Du', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 229, 'DistrictName' => 'Thành phố Từ Sơn', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 230, 'DistrictName' => 'Huyện Thuận Thành', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 231, 'DistrictName' => 'Huyện Gia Bình', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 232, 'DistrictName' => 'Huyện Lương Tài', 'CityID' => 20, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 233, 'DistrictName' => 'Thành phố Hải Dương', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 234, 'DistrictName' => 'Thành phố Chí Linh', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 235, 'DistrictName' => 'Thị xã Kinh Môn', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 236, 'DistrictName' => 'Huyện Kim Thành', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 237, 'DistrictName' => 'Huyện Thanh Hà', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 238, 'DistrictName' => 'Huyện Cẩm Giàng', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 239, 'DistrictName' => 'Huyện Bình Giang', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 240, 'DistrictName' => 'Huyện Gia Lộc', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 241, 'DistrictName' => 'Huyện Tứ Kỳ', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 242, 'DistrictName' => 'Huyện Ninh Giang', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 243, 'DistrictName' => 'Huyện Nam Sách', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 244, 'DistrictName' => 'Huyện Thanh Miện', 'CityID' => 21, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 245, 'DistrictName' => 'Thành phố Hưng Yên', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 246, 'DistrictName' => 'Huyện Văn Lâm', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 247, 'DistrictName' => 'Huyện Văn Giang', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 248, 'DistrictName' => 'Huyện Yên Mỹ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 249, 'DistrictName' => 'Thị xã Mỹ Hào', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 250, 'DistrictName' => 'Huyện Ân Thi', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 251, 'DistrictName' => 'Huyện Khoái Châu', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 252, 'DistrictName' => 'Huyện Kim Động', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 253, 'DistrictName' => 'Huyện Tiên Lữ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 254, 'DistrictName' => 'Huyện Phù Cừ', 'CityID' => 22, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 255, 'DistrictName' => 'Thành phố Thái Bình', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 256, 'DistrictName' => 'Huyện Quỳnh Phụ', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 257, 'DistrictName' => 'Huyện Hưng Hà', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 258, 'DistrictName' => 'Huyện Đông Hưng', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 259, 'DistrictName' => 'Huyện Thái Thụy', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 260, 'DistrictName' => 'Huyện Tiền Hải', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 261, 'DistrictName' => 'Huyện Kiến Xương', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
['DistrictID' => 262, 'DistrictName' => 'Huyện Vũ Thư', 'CityID' => 23, 'created_at' => now(), 'updated_at' => now()],
        ];
    }
}